package com.cometkaizo.analysis;

import com.cometkaizo.bytecode.AssembleContext;
import com.cometkaizo.monarch.structure.resource.Type;

/**
 * Indicates the bytecode generated by calling {@link com.cometkaizo.parser.Structure.Analysis#assemble(AssembleContext)}
 * on this object will have a stack effect of exactly {@link Expr#footprint()}
 */
public interface Expr {
    void assemble(AssembleContext ctx);
    Type type();
    default Size footprint() {
        return isVoid() ? Size.INVALID : type().footprint();
    }

    default boolean isVoid() {
        return type() == null;
    }
}
